// <auto-generated />
namespace sample_e_commerce_application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ecom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ecom));
        
        string IMigrationMetadata.Id
        {
            get { return "202010151607124_ecom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
